### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#494]
#450 was merged, but there are some remaining tasks we need help with:

- [x] Implement the Preferences window (needs updates based on design) (#499)
	- [x] Simplify FPS options (#418)
	- [x] Keyboard shortcuts (#150, #507)
- [x] Plugins (#500) 
	- [x] Plugin configuration (#286)
- [x] Use `electron-updater` (#258, #510) 
	- [x] Research https://electronjs.org/docs/tutorial/updates
- [x] Analytics (#463, #513) 
	- [x] Disable Sentry ([~~`raven.js`~~](https://ravenjs.com/) [`sentry-javascript`](https://github.com/getsentry/sentry-javascript)) when toggling analytics off in settings (#471, #512)
	- [x] Introduce [`insight`](https://github.com/yeoman/insight) (#89)
    	- [x] Main process
	    - [x] Renderer process (#513) 
- [x] Upgrade Next.js and ensure it works even when built (`npm run pack`) (#508)
